// Origin-state programmatic data.
//
// Per the build spec: each page must include state-specific substance (flight
// time to Austin, distance, cost-of-living contrast, savings math, and a
// state-specific FAQ). No two pages should be swappable by find-and-replace.
//
// Pages with `published: false` 404 (the [state] route refuses to render
// placeholder pages, per the no-thin-content rule). Set published: true only
// after all substantive fields are filled.
//
// Tuition figures for the in-state flagship are from each university's
// published 2025-26 tuition and required fees page. Verify before relying.
// Flight times and distances are common public knowledge for major airports.
// Cost-of-living contrast notes are derived from BEA Regional Price Parities
// and Council for Community and Economic Research data, expressed
// approximately rather than precisely.

export interface OriginState {
  slug: string;
  name: string;
  abbr: string;
  primaryAirport: string;
  flightTimeToAustinHours: number;
  drivingDistanceToAustinMiles: number;
  publicCollegeInState: string;
  inStateTuitionPublicUSD: number;
  costOfLivingNote: string;
  notableFamiliesContext: string;
  residencyMoveNote: string;
  faq: Array<{ q: string; a: string }>;
  published: boolean;
}

export const STATES: OriginState[] = [
  {
    slug: 'california',
    name: 'California',
    abbr: 'CA',
    primaryAirport: 'LAX',
    flightTimeToAustinHours: 3.0,
    drivingDistanceToAustinMiles: 1380,
    publicCollegeInState: 'University of California (UC) flagship campuses',
    inStateTuitionPublicUSD: 14_934,
    costOfLivingNote: 'Coastal California (Los Angeles, the Bay Area, San Diego) generally runs 30 to 60 percent more expensive than Austin on a comparable household basis, driven mostly by housing. Inland California (Sacramento, Fresno, the Central Valley) closes most of that gap. The headline split that surprises families: California state income tax adds up to 13.3 percent on top of federal; Texas has no state income tax. For a household earning $400,000, that is a five to six figure annual delta that frequently dominates the property carrying cost of a Rule #3 condo near UT.',
    notableFamiliesContext: 'California is one of the largest single sources of out-of-state UT Austin applications. The combination of UC system admission selectivity, the cost of California public-college housing, and the appeal of UT Austin (especially McCombs, Cockrell Engineering, and Computer Science) makes the residency pathway attractive for California families whose UC admits do not include their first choice campus.',
    residencyMoveNote: 'California residency for state purposes generally requires demonstrated intent to make California a permanent home, evidenced by California voter registration, driver license, vehicle registration, and tax filings. A California parent shifting domicile to Texas for the UT pathway should expect that California may continue to assert taxing nexus on California-source income (wages from a California employer, real estate, etc.) even after the move. The move does not have to be total: many California families keep a California residence while establishing Texas as the family domicile through the property purchase and the supporting indicia. Consult a California-licensed CPA on the franchise-tax-board residency analysis before filing your first Texas-address federal return.',
    faq: [
      { q: 'Will leaving California for Texas residency affect our California tax filings?', a: 'It can. California uses a facts-and-circumstances test for residency that looks at where you spend time, where your principal home is, and where your economic and family ties center. A clean break, with the family selling or renting out the California home and the parents physically present in Texas for most of the year, is the cleanest case. A partial move (keeping the California home, moving only the student to Texas) is harder and may require continued California filing. Talk to a California CPA before the first Texas-address federal return goes in.' },
      { q: 'Is UT Austin actually a better academic fit than UC for my student?', a: 'It depends on the major and the specific UC campus, and we are not the right venue to argue rankings. The financial comparison is more straightforward: UC in-state tuition runs roughly $14,900/year (2025-26), close to UT in-state at $11,688. UT out-of-state at $44,908 is dramatically higher. The residency pathway pulls UT down to UC-equivalent annual tuition once the 12-month clock is run.' },
      { q: 'Can we keep our California home and still qualify?', a: 'Yes, in many cases. Texas allows a person to have multiple residences but only one domicile. If the family\'s indicia of intent (driver license, vehicle, voter registration, federal tax return address) all point to Texas during the 12-month clock, owning a second home in California does not by itself defeat the petition. What does defeat it is when the documentary record shows the California home as the primary residence (homestead declaration, California voter registration, California vehicle registration) during the period when Texas domicile is claimed.' },
      { q: 'What is the most common California-family mistake?', a: 'Failing to transfer the vehicle registration in time. California Z plates are sticky, and families assume a vehicle the student drives in Austin can stay registered in California "for now." A California-registered vehicle in Texas during the 12-month clock is one of the strongest single facts against the petition. Register the vehicle in Texas within 30 days of the property closing.' },
    ],
    published: true,
  },
  {
    slug: 'new-york',
    name: 'New York',
    abbr: 'NY',
    primaryAirport: 'JFK',
    flightTimeToAustinHours: 4.0,
    drivingDistanceToAustinMiles: 1750,
    publicCollegeInState: 'SUNY (State University of New York) flagship campuses (Stony Brook, Buffalo, Binghamton)',
    inStateTuitionPublicUSD: 7_070,
    costOfLivingNote: 'New York City and the surrounding metro run 40 to 70 percent more expensive than Austin on housing-adjusted comparison. Upstate New York is closer to parity with Austin on housing but materially more expensive on energy, food, and taxes. New York state income tax tops out at 10.9 percent (plus New York City local at 3.9 percent for residents); Texas has no state income tax. For high earners, the state tax savings on a Texas move dwarf the carrying cost of a UT-area condo.',
    notableFamiliesContext: 'New York families increasingly look outside the SUNY system for selective programs, particularly in business and engineering. UT McCombs and Cockrell Engineering are well known to New York high school college counselors, and the Austin-NYC tech corridor connection (many Texas-based tech companies have NYC offices, and vice versa) makes UT alumni networks portable back to New York for graduates who return.',
    residencyMoveNote: 'New York state residency for tax purposes is determined by a domicile test plus a separate statutory-residency test (more than 183 days in New York plus a permanent place of abode). Families maintaining a permanent New York home and spending more than 183 days there will remain New York statutory residents even if they claim domicile in Texas. For the UT residency pathway, the cleanest case is a substantive household move; a part-time move with a continuing New York primary residence is harder to defend on both the Texas residency and the New York non-residency sides.',
    faq: [
      { q: 'Can a New York City family qualify for Texas residency without selling the NYC apartment?', a: 'Yes, but the documentary record needs to be tight. The federal tax return must show a Texas address. The driver license and vehicle registration should be Texas. New York City residency for tax purposes is its own analysis (the 183-day statutory rule plus permanent abode plus domicile). The two analyses can come out differently: a family can be Texas residents for UT purposes and still owe New York City tax on city-source income.' },
      { q: 'How does the New York 529 plan interact with Texas residency?', a: 'New York 529 contributions earn a state income tax deduction for New York residents. If the parents change domicile to Texas, future contributions to the New York 529 lose the state tax benefit. Withdrawals for qualified education expenses remain federally tax-free regardless of state. Some New York families pre-fund the 529 before the residency move; others migrate the 529 to a Texas plan or just discontinue contributions.' },
      { q: 'What about the New York real-estate tax break (the STAR exemption) on our NYC home?', a: 'The STAR exemption requires the property to be your primary residence. Claiming STAR during the year you are also claiming Texas domicile for UT residency creates a direct conflict in the documentary record. Withdraw the STAR exemption before petitioning.' },
      { q: 'What is the typical New York family\'s UT savings number?', a: 'New York families compare UT out-of-state (~$44,908) against in-state at SUNY flagship (~$7,070). If the student would have gone to SUNY at $7K, the residency pathway brings UT down to $11,688, $4,600/year more than SUNY. If the student would have gone out-of-state to UT regardless, the residency pathway saves the full ~$33,220/year differential.' },
    ],
    published: true,
  },
  {
    slug: 'illinois',
    name: 'Illinois',
    abbr: 'IL',
    primaryAirport: 'ORD',
    flightTimeToAustinHours: 2.5,
    drivingDistanceToAustinMiles: 1100,
    publicCollegeInState: 'University of Illinois Urbana-Champaign',
    inStateTuitionPublicUSD: 17_138,
    costOfLivingNote: 'Chicago metro and the northern suburbs run roughly 10 to 20 percent more expensive than Austin on housing-adjusted comparison; downstate Illinois is generally cheaper than Austin. Illinois state income tax is a flat 4.95 percent; Texas has no state income tax. Illinois property tax is notoriously high (2.0 to 2.5 percent of assessed value in Cook County and the collar counties), comparable to or slightly above Travis County.',
    notableFamiliesContext: 'Chicago metro families have historically sent students to Illinois (UIUC), the Big Ten (Michigan, Indiana, Wisconsin), and selective midwest privates. UT Austin has grown as a target for Chicago families seeking strong McCombs business or Cockrell engineering programs without the in-state UIUC tuition premium. The 2.5-hour flight time keeps Austin within easy weekend-visit range from O\'Hare.',
    residencyMoveNote: 'Illinois residency for income tax purposes is determined by domicile. A family establishing Texas domicile for the UT pathway should expect that Illinois may continue to claim taxing nexus on Illinois-source wages until the parent\'s primary work location relocates. Remote-work arrangements that meaningfully shift the parent\'s workplace to Texas help the Illinois non-residency case; arrangements where the parent continues to commute to a Chicago office while filing federal returns from a Texas address invite an Illinois audit.',
    faq: [
      { q: 'Is UT Austin in-state tuition really cheaper than UIUC in-state?', a: 'Yes. UIUC in-state runs approximately $17,138/year (2025-26 tuition and required fees, varies by program). UT Austin in-state at $11,688 is roughly $5,400/year cheaper. Over four years that is about $22,000 in addition to the $33,220/year savings versus out-of-state UT. For Chicago-metro families whose student would otherwise pay UIUC in-state, the UT pathway nets meaningfully cheaper four-year tuition.' },
      { q: 'What about the Illinois homestead exemption?', a: 'Illinois\'s General Homestead Exemption requires the property to be the owner\'s primary residence. Claiming it on the Illinois home while also claiming Texas domicile for UT residency is contradictory. Cook County and the collar counties also offer senior, disability, and longtime-occupant exemptions, all conditioned on primary residency. Withdraw before petitioning.' },
      { q: 'How does the Bright Start (Illinois 529) plan factor in?', a: 'Illinois Bright Start contributions earn a state income tax deduction for Illinois residents (up to $20,000 joint). After domicile shift to Texas, that deduction is gone. Federal tax treatment of withdrawals is unaffected.' },
      { q: 'My W-2 will still come from a Chicago employer for at least a year. Does that break the petition?', a: 'Not by itself. The petition will need to explain the W-2 (a remote-work arrangement, a transitional period, etc.) and the supporting documents will need to lean harder on the Texas side (property, license, vehicle, voter, address-of-record). If the W-2 box 15 (state) says Illinois and the family is filing Illinois part-year and Texas-address federal returns, the residency officer will read that as a transition in progress and weight the documentary record accordingly. If the parent continues to file Illinois full-year resident returns, the petition is much harder.' },
    ],
    published: true,
  },
  {
    slug: 'florida',
    name: 'Florida',
    abbr: 'FL',
    primaryAirport: 'MIA',
    flightTimeToAustinHours: 3.0,
    drivingDistanceToAustinMiles: 1290,
    publicCollegeInState: 'University of Florida',
    inStateTuitionPublicUSD: 6_381,
    costOfLivingNote: 'South Florida (Miami-Fort Lauderdale-Palm Beach) housing has appreciated rapidly and runs comparable to or above Austin. Central and North Florida (Orlando, Tampa, Jacksonville, Tallahassee) are generally similar to or cheaper than Austin. Both Florida and Texas have no state income tax; this is one of the few origin states where the tax-savings argument does not move the needle. The decision is more about academic fit than about state taxes.',
    notableFamiliesContext: 'Florida families send a meaningful number of students to UT Austin, especially in McCombs and the College of Natural Sciences. The University of Florida\'s in-state tuition is among the lowest in the country (~$6,381/year), which means UF is hard to beat on pure tuition cost; the UT residency pathway brings UT in-state ($11,688/year) closer to but not below UF. Florida families pursuing UT often cite specific program fit (McCombs MIS, Cockrell Engineering specialties) rather than overall cost.',
    residencyMoveNote: 'Florida and Texas are both no-income-tax states, so the headline tax-driven case for a residency move is muted. Florida\'s real-estate tax structure (Save Our Homes assessment cap, three percent annual increase limit, generous homestead exemption) is more favorable than Texas\'s ten percent cap and standard homestead. Families relocating from Florida should expect that the Florida homestead must be withdrawn (you cannot claim primary residence in both states) and that the Save Our Homes benefit on the Florida property is lost on the residency shift.',
    faq: [
      { q: 'Is UF in-state always cheaper than UT in-state for a Florida family?', a: 'Yes, on pure tuition cost. UF at roughly $6,381/year (2025-26) is about $5,300/year cheaper than UT in-state at $11,688. The case for UT pivots on program fit and the cost vs. UT out-of-state ($44,908/year), not vs. UF.' },
      { q: 'What happens to the Florida homestead exemption when we shift to Texas?', a: 'The Florida homestead exemption (and the Save Our Homes assessment cap) require the property to be the owner\'s primary residence. Withdraw the homestead declaration before petitioning for Texas residency. The reset on Save Our Homes means the next Florida tax year\'s assessment is at market value, which can be a meaningful one-time tax increase if you have held the Florida home for several years.' },
      { q: 'Does the Florida Bright Futures scholarship matter here?', a: 'Bright Futures is a Florida-state academic scholarship paid to Florida public colleges. It does not transfer to UT Austin. Florida families with Bright Futures awards typically use them at UF or another Florida public if cost is the primary driver.' },
      { q: 'We just spent four months a year in Florida and four in Texas already. Does that help our case?', a: 'It can help, if the documentary record (federal tax return address, driver license, vehicle registration, voter registration) reflects Texas during the 12-month clock. Time in Florida during the clock period needs to be explained in the petition narrative; it does not by itself defeat Texas domicile so long as the indicia point to Texas.' },
    ],
    published: true,
  },
  {
    slug: 'georgia',
    name: 'Georgia',
    abbr: 'GA',
    primaryAirport: 'ATL',
    flightTimeToAustinHours: 2.0,
    drivingDistanceToAustinMiles: 920,
    publicCollegeInState: 'University of Georgia',
    inStateTuitionPublicUSD: 12_400,
    costOfLivingNote: 'Atlanta metro housing has appreciated rapidly since 2020 and now runs roughly comparable to Austin in many submarkets. Smaller Georgia metros (Macon, Athens, Savannah) are cheaper than Austin. Georgia state income tax tops out at 5.39% (with phased reductions planned); Texas has no state income tax. The state-tax savings for high earners moving from Atlanta to Austin can be substantial.',
    notableFamiliesContext: 'Atlanta-area families increasingly look outside UGA and the Georgia Tech track for selective programs. UT McCombs and Cockrell Engineering have grown as targets for Atlanta families seeking flagship-level business or engineering programs with the Texas in-state pathway. The 2-hour flight time keeps Austin within easy weekend-visit range.',
    residencyMoveNote: 'Georgia residency for tax purposes is based on domicile plus the 183-day statutory presence test. Families maintaining a Georgia home and spending more than 183 days there will remain Georgia residents for state-tax purposes even when claiming Texas domicile for UT residency. The two analyses can come out differently. Cleanest case: substantive household move from Georgia to Texas with the Georgia home sold or converted to investment property.',
    faq: [
      { q: 'How does the Georgia HOPE Scholarship factor in for UT-bound students?', a: 'The HOPE Scholarship is a Georgia-state award payable only at Georgia public institutions. It does not transfer to UT Austin. Atlanta-area families with strong HOPE-eligible students often weigh UT (at the in-state rate after the residency pathway) vs the HOPE-funded path at UGA or Georgia Tech.' },
      { q: 'Does Atlanta-to-Austin make sense given the cost of living comparison?', a: 'Housing is roughly comparable in the inner core. Atlanta has more humidity, Austin has more allergies. Both are major tech hubs. The financial differentiator for the residency move is state income tax: Georgia\'s 5.39% top rate vs Texas\'s zero. For a household earning $300K, that\'s ~$15K/year of state-tax savings that compounds over the four years.' },
      { q: 'Will my Georgia 529 contributions still work for UT?', a: 'Yes for the withdrawals (federally qualified education expenses are unaffected by state of residency). The state-tax deduction Georgia residents receive for in-state 529 contributions does not transfer to Texas residents. If you stop being a Georgia resident, contributions made before the move retain their tax basis; contributions after the move are not Georgia-tax-deductible.' },
      { q: 'My W-2 will still come from Atlanta for a year or two while I transition. Does that block the petition?', a: 'It complicates but does not block. The petition will explain the transitional employment situation. The other documentary indicia (driver license, vehicle, voter registration, federal tax return address) should clearly point to Texas. Filing a Georgia non-resident return and a federal return with the Texas address for the relevant tax year typically holds together.' },
    ],
    published: true,
  },
  {
    slug: 'washington',
    name: 'Washington',
    abbr: 'WA',
    primaryAirport: 'SEA',
    flightTimeToAustinHours: 4.0,
    drivingDistanceToAustinMiles: 2200,
    publicCollegeInState: 'University of Washington',
    inStateTuitionPublicUSD: 12_700,
    costOfLivingNote: 'Seattle metro and the eastside (Bellevue, Redmond, Kirkland) are among the most expensive housing markets in the US. Austin housing runs 30-50% cheaper than comparable Seattle-area neighborhoods. Both Washington and Texas have no state income tax, so the tax-driven case for the move is muted (similar to Florida). The case becomes primarily about UT program fit and Austin lifestyle.',
    notableFamiliesContext: 'Microsoft, Amazon, Boeing, and the broader Seattle tech corridor have built a population of high-earning families whose students often consider UT for CS, Engineering, and McCombs. The cross-country travel time is the main friction; 4 hours direct from SEA to AUS.',
    residencyMoveNote: 'Washington state residency analysis is straightforward because Washington has no state income tax. The move to Texas does not create complex tax-residency questions on the Washington side. Property in Washington (often the family\'s primary residence) needs to either be sold, converted to rental, or maintained as a second home with the supporting indicia clearly pointing to Texas for the 12-month residency clock.',
    faq: [
      { q: 'Why would a Washington family go to UT instead of UW?', a: 'UW direct admission to CS, the Foster School of Business, and Engineering can be difficult; UT has slightly different admission patterns and some programs are easier to access. UT also has a different culture (Austin music/food scene vs Seattle) that families weigh. The financial math after the residency pathway brings UT roughly to parity with UW in-state, both around $12K/year.' },
      { q: 'How much will the Washington-to-Texas state tax savings be?', a: 'Very little, because neither state taxes income. The financial case for the move is primarily about UT in-state tuition reducing the four-year bill by ~$99,660 vs UT out-of-state.' },
      { q: 'Can I keep my Seattle home while my child attends UT?', a: 'Yes, structurally. The trick is the documentary record: if the Washington home is still your primary residence for federal tax purposes, the federal return for the relevant year reflects a Washington address. UT\'s residency office sees that and concludes you remained domiciled in Washington. The fix is to file federal returns with the Texas address as primary residence during the 12-month clock, which generally means either selling the Washington home, converting it to rental property reported on Schedule E, or genuinely treating the Texas property as the primary household.' },
      { q: 'How does the 4-hour flight affect parent visit patterns?', a: 'Most Seattle-area UT parents fly in 2-3 times per year (move-in, mid-fall visit, graduation/spring), with the student flying home for breaks. Flight cost runs $300-$500 round-trip on Alaska or Delta. Annual travel budget: $2,500-$4,000.' },
    ],
    published: true,
  },
  {
    slug: 'massachusetts',
    name: 'Massachusetts',
    abbr: 'MA',
    primaryAirport: 'BOS',
    flightTimeToAustinHours: 4.0,
    drivingDistanceToAustinMiles: 1900,
    publicCollegeInState: 'University of Massachusetts Amherst',
    inStateTuitionPublicUSD: 17_300,
    costOfLivingNote: 'Boston metro, especially Cambridge, Brookline, Newton, and the western suburbs, ranks among the most expensive US housing markets. Austin housing runs significantly cheaper than comparable Boston-area neighborhoods. Massachusetts state income tax is a flat 5% (with a 4% millionaire surtax on income above $1M); Texas has no state income tax. The tax savings for high-earning Boston-area families moving to Texas are meaningful.',
    notableFamiliesContext: 'Boston-area families considering UT often have students admitted to or interested in McCombs, CS, or Plan II Honors. The strong Boston-to-Texas tech connection (many MIT and Northeastern alumni in Austin) means the cultural transition feels less jarring than parents expect. UT alumni networks in Boston are growing but still smaller than the East Coast counterparts.',
    residencyMoveNote: 'Massachusetts residency for tax purposes uses a domicile-plus-183-day test. Families maintaining a Massachusetts home and spending more than 183 days there will remain Massachusetts statutory residents even when claiming Texas domicile. For the UT residency pathway, the cleanest case is a substantive household move; a part-time arrangement is harder to defend on both ends.',
    faq: [
      { q: 'Is UT at the in-state rate really cheaper than UMass Amherst?', a: 'Yes. UMass Amherst in-state runs roughly $17,300/year. UT at the resident rate is $11,688/year. That is about $5,600/year cheaper at UT, or $22,400 over four years. Combined with the $99,660 saved vs UT out-of-state, the cumulative four-year delta vs the do-nothing scenario is substantial.' },
      { q: 'How does the Massachusetts 529 (U.Plan and U.Fund) interact with Texas residency?', a: 'Massachusetts 529 contributions earn a state income tax deduction (up to $1,000 single, $2,000 joint). After residency shift to Texas, that deduction is gone. Federal tax treatment of withdrawals for qualified education expenses is unaffected.' },
      { q: 'My W-2 will keep coming from a Boston employer. How does that affect the petition?', a: 'It complicates but does not block. UT\'s residency office will see the Massachusetts W-2 and the petition narrative needs to explain it (remote work from Texas, transitional employment, etc.). The other documentary indicia should clearly point to Texas. Filing a Massachusetts non-resident return for the year of move plus a federal return with the Texas address is the typical structure.' },
      { q: 'What about the Boston-to-Austin flight time and frequency?', a: '4-hour direct flights on JetBlue, Delta, American. Many Boston-area UT parents fly in 2-3 times per year. Round-trip fares run $200-$400 outside peak. Annual travel budget for the family: $2,500-$4,000.' },
    ],
    published: true,
  },
  {
    slug: 'virginia',
    name: 'Virginia',
    abbr: 'VA',
    primaryAirport: 'DCA',
    flightTimeToAustinHours: 3.0,
    drivingDistanceToAustinMiles: 1500,
    publicCollegeInState: 'University of Virginia',
    inStateTuitionPublicUSD: 22_300,
    costOfLivingNote: 'Northern Virginia (Fairfax, Arlington, McLean) is among the most expensive US housing markets and runs 40-70% above Austin pricing. Outside the DC metro, Virginia is more comparable to Austin. Virginia state income tax tops out at 5.75% (Northern Virginia families often pay significant local taxes too); Texas has no state income tax. The tax-savings argument for the move is meaningful for high earners.',
    notableFamiliesContext: 'Northern Virginia families with students admitted to UVA, William & Mary, or Virginia Tech also frequently consider UT, especially for McCombs Business and Cockrell Engineering. The DC-to-Austin connection is strong because both metros have heavy government-adjacent industries (federal contracting, biotech, defense). UVA in-state tuition at $22,300 is one of the highest in the US, making UT at the in-state rate dramatically cheaper.',
    residencyMoveNote: 'Virginia residency for tax purposes is determined by domicile. Maintaining a Virginia home while spending most of the year there will continue Virginia residency. A substantive move to Texas is the cleanest path. The $200-day rule for Virginia statutory residency adds complexity for families splitting time.',
    faq: [
      { q: 'Why would a Virginia family go to UT instead of UVA?', a: 'UVA in-state at $22,300/year is more expensive than UT in-state at $11,688/year, so for families who do successfully establish Texas residency, UT is cheaper than the home-state flagship. Over four years, the difference is ~$42,000. Plus the UT program fit (especially McCombs and Cockrell) may suit certain students better than UVA\'s offerings.' },
      { q: 'My family has VEA / Virginia 529 plan contributions. What happens?', a: 'Virginia 529 contributions earn a state income tax deduction (up to $4,000 per beneficiary per year, with unlimited rollover). After the move to Texas, that deduction is gone but the existing contributions retain their tax basis. Withdrawals for qualified expenses remain federally tax-free.' },
      { q: 'Does living in Northern Virginia complicate the Texas residency move?', a: 'NoVa\'s high cost of living actually makes the move easier financially because Austin housing is cheaper. The tax savings (no Texas income tax) plus the lower housing cost can fund the Texas property carrying cost. The complication is family ties (DC-area jobs, schools for younger siblings). Many families do the move in phases.' },
      { q: 'How is the DC-to-Austin flight time?', a: 'About 3 hours direct on American, United, Southwest. Frequent service. Round-trip fares $200-$450. Annual family travel budget: $2,000-$3,500.' },
    ],
    published: true,
  },
  {
    slug: 'new-jersey',
    name: 'New Jersey',
    abbr: 'NJ',
    primaryAirport: 'EWR',
    flightTimeToAustinHours: 4.0,
    drivingDistanceToAustinMiles: 1740,
    publicCollegeInState: 'Rutgers University, New Brunswick',
    inStateTuitionPublicUSD: 17_600,
    costOfLivingNote: 'New Jersey housing runs 30-80% above Austin depending on the town. Bergen County, Morris County, and the desirable shore communities are among the most expensive in the US. New Jersey state income tax tops out at 10.75% and the state has high property taxes (highest median in the US at ~2.4%). Texas has no state income tax and lower property tax rates. Tax savings from a NJ-to-TX move are substantial.',
    notableFamiliesContext: 'NJ families historically send students to Rutgers, NJIT, Princeton, and the Ivies. UT has grown as a target especially for CS, McCombs, and Liberal Arts. The relatively cheap Austin housing vs the impossibly expensive NJ housing makes the math attractive for families who can stomach the move.',
    residencyMoveNote: 'New Jersey residency for tax purposes uses domicile plus statutory presence tests. Families maintaining the NJ home and continuing to work in the metro area will struggle to defend the Texas residency claim on the tax side. Cleanest case: substantive household move with the NJ home sold or converted, plus parental remote-work arrangement that supports Texas as the primary domicile.',
    faq: [
      { q: 'Is UT in-state really cheaper than Rutgers?', a: 'Yes. Rutgers in-state runs about $17,600/year. UT at the resident rate is $11,688. About $6,000/year cheaper or ~$24,000 over four years. Combined with the $99,660 saved vs UT out-of-state, the cumulative four-year financial impact is meaningful.' },
      { q: 'How much state income tax would I save moving from NJ to Texas?', a: 'For a household earning $500K in NJ, the NJ state tax burden runs roughly $35K-$40K/year. Texas: zero. The four-year state-tax savings of $140K-$160K alone substantially funds the Texas property purchase and carrying costs.' },
      { q: 'What about the high NJ property tax I currently pay?', a: 'NJ property tax averages 2.4% of assessed value, among the highest in the US. Travis County (Austin) runs 2.0-2.3%. The savings on the property tax side are smaller but help. The bigger win is the income tax differential.' },
      { q: 'Will my NJ employer let me work from Texas?', a: 'It depends. The NJ-to-NY-to-Austin remote work pattern has become more accepted post-2020. Some employers require NJ presence; others are fully remote-friendly. Confirm with HR before committing to the move; some employers will require state tax withholding still be done in the NJ system.' },
    ],
    published: true,
  },
  {
    slug: 'colorado',
    name: 'Colorado',
    abbr: 'CO',
    primaryAirport: 'DEN',
    flightTimeToAustinHours: 2.5,
    drivingDistanceToAustinMiles: 980,
    publicCollegeInState: 'University of Colorado Boulder',
    inStateTuitionPublicUSD: 14_600,
    costOfLivingNote: 'Denver and Boulder housing have appreciated significantly in the past decade and run roughly comparable to Austin pricing for similar properties. Colorado state income tax is a flat 4.4%; Texas has no state income tax. The tax savings are modest but meaningful for high earners.',
    notableFamiliesContext: 'Colorado families consider UT particularly for McCombs Business, Cockrell Engineering, and Plan II Honors. The Denver-to-Austin tech corridor has grown substantially. Both metros share an outdoorsy, tech-heavy culture, so the move feels familiar to Colorado families.',
    residencyMoveNote: 'Colorado residency for tax purposes is determined by domicile. The move to Texas is straightforward when the family genuinely transitions. Maintaining the Colorado home requires careful documentary attention to ensure the federal tax return shows Texas as the residence of record.',
    faq: [
      { q: 'Is UT in-state really cheaper than CU Boulder?', a: 'Yes, by about $3,000/year. CU Boulder runs $14,600 in-state; UT runs $11,688. Over four years, $12,000 cheaper. Plus the $99,660 saved vs UT out-of-state, the cumulative financial impact is meaningful.' },
      { q: 'How does Colorado state tax compare to Texas?', a: 'Colorado flat 4.4%. Texas zero. For a $300K household, that\'s ~$13K/year of state-tax savings. Modest but worthwhile.' },
      { q: 'Can I keep my Denver or Boulder home while my child attends UT?', a: 'Yes, with documentary care. The federal tax return for the relevant year must show Texas as the primary residence. Selling the Colorado home or converting to rental property simplifies the case. Keeping it as a second home is workable but requires clear narrative.' },
      { q: 'How is the Denver-to-Austin flight?', a: '2.5 hours direct on Southwest, Frontier, American, United. Round-trip fares $150-$350. Easy weekend visits. Annual family travel budget: $1,500-$3,000.' },
    ],
    published: true,
  },
  {
    slug: 'tennessee',
    name: 'Tennessee',
    abbr: 'TN',
    primaryAirport: 'BNA',
    flightTimeToAustinHours: 1.75,
    drivingDistanceToAustinMiles: 870,
    publicCollegeInState: 'University of Tennessee Knoxville',
    inStateTuitionPublicUSD: 13_900,
    costOfLivingNote: 'Nashville housing has appreciated dramatically since 2020 and now runs comparable to Austin in many submarkets. Memphis, Knoxville, and Chattanooga remain cheaper than Austin. Tennessee has no state income tax, the same as Texas, so the state-tax case for the move is muted. The argument is primarily UT program fit and the long-term Austin property thesis.',
    notableFamiliesContext: 'Nashville-area families have grown as a UT applicant pipeline, especially for McCombs Business (because Nashville is a major business and music industry hub with strong UT alumni connections) and Cockrell Engineering. Memphis sends a smaller but consistent number of students. The 1.75-hour Nashville-to-Austin flight is among the shortest from any major non-Texas city.',
    residencyMoveNote: 'Tennessee residency analysis is straightforward because Tennessee has no state income tax to disentangle. The standard property pathway works cleanly: acquire Texas real estate, build the supporting indicia, file federal returns with the Texas address. Most Tennessee families completing the move keep their Tennessee home as either an investment property or a sold asset.',
    faq: [
      { q: 'Why move from Tennessee to establish Texas residency when both states have no income tax?', a: 'The primary driver is UT in-state tuition vs UT out-of-state tuition: ~$33,000/year saved. Tennessee residency at UT would mean paying $44,908/year as out-of-state, which is roughly 3.8x the in-state rate. The four-year savings from establishing Texas residency is approximately $99,660 in the typical scenario.' },
      { q: 'Is UT Austin actually a better academic fit than UT Knoxville for my student?', a: 'It depends entirely on major and the specific UT Knoxville vs UT Austin comparison. UT Austin generally ranks higher in business (McCombs) and engineering (Cockrell). UT Knoxville is strong in agricultural sciences and several engineering disciplines. The cost difference once residency is established is small ($11,688 vs $13,900), so the decision is academic fit, not cost.' },
      { q: 'How is the Nashville-to-Austin flight pattern?', a: 'Direct flights on Southwest, American, and increasingly United run $150-$300 round-trip outside peak season. Frequent service with multiple daily flights. Easy weekend visits. Annual family travel budget: $2,000-$3,500.' },
      { q: 'My family has a Tennessee 529 plan (TNStars). What happens if we shift residency to Texas?', a: 'Tennessee 529 contributions earn no state tax deduction (because Tennessee has no income tax), so there is nothing to lose on that front. Existing balances retain their tax basis. Withdrawals for qualified education expenses remain federally tax-free regardless of state.' },
    ],
    published: true,
  },
  {
    slug: 'pennsylvania',
    name: 'Pennsylvania',
    abbr: 'PA',
    primaryAirport: 'PHL',
    flightTimeToAustinHours: 3.5,
    drivingDistanceToAustinMiles: 1640,
    publicCollegeInState: 'Penn State University Park',
    inStateTuitionPublicUSD: 19_600,
    costOfLivingNote: 'Philadelphia suburbs (Main Line, Bucks County, Montgomery County) and Pittsburgh metro vary widely in cost. The Philadelphia suburbs run roughly comparable to Austin or slightly more expensive; Pittsburgh runs noticeably cheaper. Pennsylvania state income tax is a flat 3.07%, plus local earned income taxes (often 1-3% additional in cities). Texas has no state income tax. The combined state-plus-local tax savings for moving to Texas can be meaningful for high earners.',
    notableFamiliesContext: 'Philadelphia and Pittsburgh metro families consider UT especially for McCombs Business, Cockrell Engineering, and CS. Penn State at $19,600/year in-state is among the more expensive flagship publics, so UT after residency ($11,688/year) is meaningfully cheaper than Penn State at the home rate.',
    residencyMoveNote: 'Pennsylvania residency for tax purposes is determined by domicile plus a 30-day statutory presence test. Moving the family\'s primary residence to Texas and selling or converting the Pennsylvania home is the cleanest case. Maintaining the Pennsylvania home while spending most of the year there will continue Pennsylvania residency and complicate the petition narrative.',
    faq: [
      { q: 'Is UT after residency really cheaper than Penn State in-state?', a: 'Yes. Penn State in-state runs ~$19,600/year. UT at the resident rate is $11,688. That is about $7,900/year cheaper or ~$31,600 over four years. Combined with the $99,660 saved vs UT out-of-state, the four-year financial picture is meaningful.' },
      { q: 'How does Pennsylvania state and local tax compare?', a: 'Pennsylvania flat state income tax of 3.07%, plus most municipalities charge a 1-3% local earned income tax (Philadelphia is 3.75% for residents). Texas has neither. For a household earning $300K in Philadelphia, that is ~$20,000/year of tax savings on a move to Texas.' },
      { q: 'My PA 529 (PA529 IP or GSP) has been accumulating. What happens?', a: 'Pennsylvania residents earn a state income tax deduction for contributions to any 529 plan (not just Pennsylvania\'s). After moving to Texas, that deduction is gone but the existing balances retain their tax basis. Withdrawals for qualified education expenses are federally tax-free regardless of state.' },
      { q: 'My W-2 will still come from a Philadelphia employer for a year. Does that block the petition?', a: 'It complicates but does not block. The petition narrative needs to explain the transitional employment situation. The other documentary indicia (driver license, vehicle, voter, federal tax return address) should clearly point to Texas. Filing a Pennsylvania part-year resident return plus a federal return with a Texas address for the relevant tax year is the typical structure.' },
    ],
    published: true,
  },
  {
    slug: 'ohio',
    name: 'Ohio',
    abbr: 'OH',
    primaryAirport: 'CMH',
    flightTimeToAustinHours: 2.5,
    drivingDistanceToAustinMiles: 1180,
    publicCollegeInState: 'Ohio State University',
    inStateTuitionPublicUSD: 13_000,
    costOfLivingNote: 'Columbus, Cleveland, and Cincinnati housing all run noticeably cheaper than Austin. Ohio state income tax tops out at 3.5%, with most households in the 2-3% range; Texas has no state income tax. The cost-of-living differential favors Ohio on housing but Texas on taxes. For high earners, the combined picture varies by household.',
    notableFamiliesContext: 'Ohio families have a strong tradition of attending Ohio State as the home flagship. UT Austin draws from Ohio for specific programs (McCombs Business, Cockrell Engineering, Plan II Honors) where the program fit beats the home option. The 2.5-hour Columbus-to-Austin flight keeps it in easy weekend range.',
    residencyMoveNote: 'Ohio residency for tax purposes uses a domicile test plus statutory residency rules. The move to Texas is straightforward when the family genuinely transitions. The Ohio property either needs to be sold, converted to rental, or maintained as a secondary residence with the supporting indicia clearly pointing to Texas.',
    faq: [
      { q: 'Is UT after residency really cheaper than Ohio State in-state?', a: 'Yes, by about $1,300/year. Ohio State runs ~$13,000/year in-state; UT runs $11,688. The bigger driver is vs UT out-of-state where the savings approach $33,000/year.' },
      { q: 'How does Ohio state tax compare to Texas?', a: 'Ohio tops out at 3.5% with most households in the 2-3% range. Texas has zero. For a $300K household, ~$8K/year of state-tax savings on the move.' },
      { q: 'Can I keep my Ohio home and still establish Texas residency?', a: 'Yes, with documentary care. The federal tax return for the relevant year must show a Texas address. Selling the Ohio home or converting to rental property simplifies the case substantially.' },
      { q: 'How is the Columbus-to-Austin flight?', a: '2.5 hours direct on Southwest and American. Round-trip fares $150-$350. Easy weekend visits.' },
    ],
    published: true,
  },
  {
    slug: 'michigan',
    name: 'Michigan',
    abbr: 'MI',
    primaryAirport: 'DTW',
    flightTimeToAustinHours: 2.75,
    drivingDistanceToAustinMiles: 1370,
    publicCollegeInState: 'University of Michigan',
    inStateTuitionPublicUSD: 17_700,
    costOfLivingNote: 'Detroit suburbs (Ann Arbor, Birmingham, Bloomfield Hills, Grosse Pointe) and Grand Rapids all run cheaper than Austin on housing. Michigan state income tax is a flat 4.05%; Texas has no state income tax. The combined picture favors Michigan slightly on housing and Texas on income tax.',
    notableFamiliesContext: 'Michigan families with students admitted to U-M as in-state often weigh UT as an alternative for specific programs. UT McCombs vs Ross Business, UT Cockrell vs Michigan Engineering. The financial calculus is interesting because Michigan in-state at $17,700 is one of the more expensive flagship publics, so UT after residency ($11,688) is ~$6,000/year cheaper than Michigan at the home rate.',
    residencyMoveNote: 'Michigan residency for tax purposes is determined by domicile plus a 183-day statutory residence test. Maintaining the Michigan home while spending most of the year there will keep Michigan residency. A substantive household move with Texas property as the primary residence is the cleanest path.',
    faq: [
      { q: 'Is UT after residency really cheaper than University of Michigan in-state?', a: 'Yes, materially. U-M in-state at ~$17,700 is significantly above UT in-state at $11,688. The four-year savings from going to UT instead of U-M (assuming Texas residency is established) is approximately $24,000. Combined with the savings vs UT out-of-state of $99,660, the cumulative financial impact is meaningful.' },
      { q: 'How does Michigan state tax compare to Texas?', a: 'Michigan flat 4.05%. Texas zero. For a $300K household, ~$11K/year of state-tax savings.' },
      { q: 'My family has a Michigan 529 (MESP or MAP). What happens?', a: 'Michigan residents earn a state income tax deduction for Michigan 529 contributions (up to $5,000 single, $10,000 joint). After moving to Texas, that deduction is gone but existing balances retain their basis. Withdrawals for qualified education remain federally tax-free.' },
      { q: 'How is the Detroit-to-Austin flight?', a: '2.75 hours direct on Spirit, Delta, Southwest. Round-trip fares $150-$350. Reasonable weekend visit range.' },
    ],
    published: true,
  },
  {
    slug: 'maryland',
    name: 'Maryland',
    abbr: 'MD',
    primaryAirport: 'BWI',
    flightTimeToAustinHours: 3.0,
    drivingDistanceToAustinMiles: 1500,
    publicCollegeInState: 'University of Maryland College Park',
    inStateTuitionPublicUSD: 12_400,
    costOfLivingNote: 'Montgomery County, Howard County, and the DC-suburbs of Maryland run among the most expensive US housing markets. Baltimore proper is significantly cheaper. Maryland state income tax tops out at 5.75% (plus county piggyback taxes of 2.25-3.2%), so the combined Maryland-plus-county tax rate often exceeds 8% on high earners. Texas has no state income tax. The tax savings from a Maryland-to-Texas move can be very substantial.',
    notableFamiliesContext: 'Maryland families, especially those in Montgomery and Howard County, increasingly consider UT for McCombs Business, CS, Plan II Honors, and Cockrell Engineering. The Maryland-DC tech corridor produces high-earning households whose students often weigh UT against the in-state UMD option. UMD at $12,400 is close enough to UT in-state at $11,688 that the cost-only argument is small once residency is established.',
    residencyMoveNote: 'Maryland residency for tax purposes uses a domicile-plus-183-day test. The DC-area employment patterns make the residency-shift analysis more complex; many Maryland-based households have one earner in DC and another in Maryland, and the family\'s primary domicile can be debated. A clean Texas-residency case typically requires substantive household relocation.',
    faq: [
      { q: 'Is UT after residency cheaper than UMD in-state?', a: 'Slightly, by about $700/year. UMD runs ~$12,400/year in-state; UT runs $11,688. The bigger driver is vs UT out-of-state ($33,220/year savings).' },
      { q: 'How does Maryland state and county tax compare to Texas?', a: 'Maryland state tax tops out at 5.75% plus county piggyback taxes of 2.25-3.2%. Combined effective rate for a high-earning Montgomery County household runs ~8%. Texas: zero. For a $400K household, ~$32K/year of tax savings.' },
      { q: 'Will my Maryland 529 plan still work?', a: 'Yes for federal-tax-free qualified withdrawals. Maryland residents earn a state income tax deduction for Maryland 529 contributions. After moving to Texas, that deduction is gone but the contributions retain their basis.' },
      { q: 'How is the BWI-to-Austin flight?', a: '3 hours direct on Southwest, American, United. Round-trip fares $200-$450. Reasonable weekend range.' },
    ],
    published: true,
  },
  {
    slug: 'north-carolina',
    name: 'North Carolina',
    abbr: 'NC',
    primaryAirport: 'CLT',
    flightTimeToAustinHours: 2.5,
    drivingDistanceToAustinMiles: 1170,
    publicCollegeInState: 'University of North Carolina Chapel Hill',
    inStateTuitionPublicUSD: 9_000,
    costOfLivingNote: 'Charlotte and the Triangle (Raleigh-Durham-Chapel Hill) have appreciated rapidly but still run roughly comparable to or slightly cheaper than Austin. Smaller NC metros (Asheville, Wilmington, Greensboro) are noticeably cheaper than Austin. North Carolina state income tax is a flat 4.5%; Texas has none. The state-tax case for moving is modest.',
    notableFamiliesContext: 'North Carolina has a strong tradition of attending UNC or NC State as the home flagship at the country\'s lowest in-state public tuition ($9,000/year at UNC). The case for moving to Texas residency for UT is harder financially because UNC in-state is dramatically cheaper than UT in-state. NC families considering UT typically do so for specific program fit (McCombs, CS) or because the student was not admitted to UNC.',
    residencyMoveNote: 'North Carolina residency for tax purposes is determined by domicile. The move to Texas is straightforward; the NC property either sold, rented, or maintained as a second home with clear Texas-primary indicia.',
    faq: [
      { q: 'UNC in-state at $9,000 is cheaper than UT in-state. Why would I move to Texas?', a: 'Only if your student was not admitted to UNC, or there is a specific program fit at UT (McCombs Business, CS, Plan II Honors) that justifies the cost difference. If UNC is an option, the math typically does not justify the residency move purely on cost.' },
      { q: 'How does NC state tax compare to Texas?', a: 'NC flat 4.5%. Texas zero. For a $300K household, ~$13K/year tax savings.' },
      { q: 'Is UT really worth more than UNC academically?', a: 'It depends on major. UT McCombs and UNC Kenan-Flagler are roughly peers in business; UT Cockrell and NC State engineering are not strictly comparable but both strong. UT has Plan II Honors as a distinctive offering. UNC has its own distinctive programs. Not a one-way decision.' },
      { q: 'How is the Charlotte-to-Austin flight?', a: '2.5 hours direct on American and Spirit. Round-trip fares $150-$350. Good weekend range.' },
    ],
    published: true,
  },
  {
    slug: 'indiana',
    name: 'Indiana',
    abbr: 'IN',
    primaryAirport: 'IND',
    flightTimeToAustinHours: 2.0,
    drivingDistanceToAustinMiles: 1080,
    publicCollegeInState: 'Indiana University Bloomington',
    inStateTuitionPublicUSD: 11_900,
    costOfLivingNote: 'Indianapolis and the Indianapolis suburbs (Carmel, Fishers, Zionsville) are noticeably cheaper than Austin on housing. Indiana state income tax is a flat 3.0%, plus county income tax of 0.5-3.4%. Texas has none. The combined Indiana-plus-county tax can run 4-6%; Texas is zero. The state-tax savings are modest but help.',
    notableFamiliesContext: 'Indiana families typically attend Indiana University or Purdue. UT is a target for specific programs (McCombs Business especially, given the strong Indianapolis business community connection). The financial cost calculus is roughly neutral between IU and UT after residency because the in-state tuition rates are similar.',
    residencyMoveNote: 'Indiana residency analysis is straightforward. The Indianapolis-area to Austin move pattern is common and well-trodden. Many Carmel and Fishers families have done this move and have shared experiences.',
    faq: [
      { q: 'Is UT after residency cheaper than IU in-state?', a: 'Marginally. IU at ~$11,900/year, UT at $11,688. About $200/year cheaper at UT. The big driver is vs UT out-of-state where the savings are $33,000+/year.' },
      { q: 'How does Indiana state and county tax compare?', a: 'Indiana flat 3.0% state + 0.5-3.4% county = combined 4-6%. Texas: zero. For a $300K household, ~$12-15K/year of tax savings depending on county.' },
      { q: 'My family has CollegeChoice 529 (Indiana). What happens?', a: 'Indiana residents earn a 20% state income tax credit (up to $1,500/year) for contributions to CollegeChoice 529. After moving to Texas, that credit is gone. Existing balances retain basis.' },
      { q: 'How is the Indianapolis-to-Austin flight?', a: '2 hours direct on Southwest. Round-trip fares $130-$300. Excellent weekend range.' },
    ],
    published: true,
  },
  {
    slug: 'minnesota',
    name: 'Minnesota',
    abbr: 'MN',
    primaryAirport: 'MSP',
    flightTimeToAustinHours: 2.75,
    drivingDistanceToAustinMiles: 1230,
    publicCollegeInState: 'University of Minnesota Twin Cities',
    inStateTuitionPublicUSD: 16_700,
    costOfLivingNote: 'Minneapolis-Saint Paul housing runs roughly comparable to Austin in most submarkets. Outside the Twin Cities, Minnesota is noticeably cheaper than Austin. Minnesota state income tax tops out at 9.85%, among the highest in the US; Texas has none. The state-tax case for a Minnesota-to-Texas move is very strong for high earners.',
    notableFamiliesContext: 'Twin Cities families consider UT especially for McCombs Business, Cockrell Engineering, and Plan II Honors. U-Minn at $16,700 in-state is significantly more expensive than UT in-state, so the post-residency UT cost ($11,688/year) is meaningfully cheaper than U-Minn at the home rate. The Minneapolis tech corridor produces a high-earning population that values flagship-level programs.',
    residencyMoveNote: 'Minnesota residency for tax purposes uses a domicile plus 183-day statutory residence test. The high Minnesota state income tax makes the case for substantive household relocation strong. Many high-earning Twin Cities families have already considered the move for tax reasons; the UT residency angle gives an additional dimension.',
    faq: [
      { q: 'Is UT after residency cheaper than U-Minn in-state?', a: 'Yes, materially. U-Minn at ~$16,700, UT at $11,688. About $5,000/year cheaper, or $20,000 over four years.' },
      { q: 'How does Minnesota state tax compare to Texas?', a: 'Minnesota tops out at 9.85%. Texas zero. For a $400K Minnesota household, that is ~$30K/year of tax savings. Over four years, $120,000+.' },
      { q: 'Will my Minnesota 529 plan still work?', a: 'Yes for federal-tax-free qualified withdrawals. Minnesota residents earn a state income tax deduction or credit for 529 contributions. After moving to Texas, that benefit is gone but existing balances retain basis.' },
      { q: 'How is the MSP-to-Austin flight?', a: '2.75 hours direct on Sun Country, Delta, Spirit. Round-trip fares $200-$400. Reasonable weekend range, though Minneapolis weather makes winter travel less predictable.' },
    ],
    published: true,
  },
  {
    slug: 'arizona',
    name: 'Arizona',
    abbr: 'AZ',
    primaryAirport: 'PHX',
    flightTimeToAustinHours: 2.0,
    drivingDistanceToAustinMiles: 1020,
    publicCollegeInState: 'University of Arizona',
    inStateTuitionPublicUSD: 13_200,
    costOfLivingNote: 'Phoenix and Tucson housing run cheaper than Austin in most submarkets. Scottsdale and Paradise Valley run roughly comparable to Austin. Arizona state income tax is a flat 2.5% (one of the lowest in the country); Texas has zero. The state-tax move is modest.',
    notableFamiliesContext: 'Arizona families consider UT for CS, McCombs, and the College of Natural Sciences. The Phoenix metro\'s rapid growth has created a high-earner population interested in flagship-public alternatives to ASU and Arizona. The 2-hour Phoenix-to-Austin flight keeps it within reach.',
    residencyMoveNote: 'Arizona residency for tax purposes is straightforward. Move documentation requires the standard property and indicia. Arizona\'s relatively low income tax means the tax savings from moving to Texas are modest, but the UT tuition savings remain the primary financial driver.',
    faq: [
      { q: 'Why move from Arizona to establish Texas residency? Arizona is already cheap.', a: 'Two reasons: (1) UT is a flagship destination with programs that ASU and Arizona may not offer at the same level; (2) Texas property typically appreciates faster than Arizona property, and the residency purchase functions as a real estate investment in a growing market.' },
      { q: 'Is UT in-state really cheaper than Arizona in-state?', a: 'Yes. Arizona runs $13,200/year, UT runs $11,688. About $1,500/year cheaper or ~$6,000 over four years. The bigger financial driver is vs UT out-of-state ($99,660 saved).' },
      { q: 'How does the AZ-to-TX state tax compare?', a: 'Arizona flat 2.5%, Texas zero. For most households the difference is modest ($1,000-$5,000/year). Not the primary driver of the move.' },
      { q: 'How is the Phoenix-to-Austin flight?', a: '2 hours direct on American, Southwest, Frontier. Round-trip fares $150-$300. Easy weekend visits.' },
    ],
    published: true,
  },
  {
    slug: 'oklahoma',
    name: 'Oklahoma',
    abbr: 'OK',
    primaryAirport: 'OKC',
    flightTimeToAustinHours: 1.5,
    drivingDistanceToAustinMiles: 400,
    publicCollegeInState: 'University of Oklahoma',
    inStateTuitionPublicUSD: 12_500,
    costOfLivingNote: 'Oklahoma City and Tulsa cost of living is materially lower than Austin (Oklahoma housing runs 40-50% below Austin). Oklahoma state income tax tops out at 4.75%; Texas has zero. For high earners, the tax move alone can save $10,000-$25,000/year.',
    notableFamiliesContext: 'Oklahoma families consider UT for the same reasons Texas families do: McCombs, CS, Cockrell Engineering, plus the Austin opportunity ecosystem. The 400-mile drive from Oklahoma City to Austin makes it one of the most accessible out-of-state markets for UT. Many Oklahoma families maintain ties to Oklahoma (oil and gas families, agricultural businesses) while pursuing the Texas residency pathway.',
    residencyMoveNote: 'Oklahoma residency is straightforward to exit. The standard documentary set (Texas driver\'s license, vehicle registration, voter registration, Texas-address federal tax return, and Texas property or lease) establishes Texas residency in 12 months. The Oklahoma-to-Austin drive (5.5 hours) makes maintenance of the new domicile easy: Texas-titled vehicle, Texas voter registration, and so on. The tax savings from exiting Oklahoma\'s income tax usually offset most Texas property tax.',
    faq: [
      { q: 'Why move from Oklahoma to Texas when OU is cheaper?', a: 'OU in-state at $12,500 is about $800/year more expensive than UT in-state at $11,688. For a student admitted to McCombs, UT CS, or Cockrell Engineering, UT\'s programs significantly outrank OU\'s comparable programs. The Texas residency pathway is also a real-estate opportunity (Austin appreciation outpaces Oklahoma City) and a state-income-tax escape ($10,000-$25,000/year for high earners).' },
      { q: 'Can my student commute from Oklahoma to UT?', a: 'No. UT requires substantive physical presence in Texas for residency reclassification. The student must actually live in Texas at the petitioned-for residence.' },
      { q: 'How does Oklahoma-to-Texas tax compare?', a: 'Oklahoma top rate is 4.75%; Texas zero. For a household with $300K AGI, the state tax savings is approximately $14,000/year. Plus Oklahoma\'s gross production tax (oil/gas) has no parallel in Texas (Texas has its own oil/gas tax but the structure differs).' },
      { q: 'How is the OKC-to-Austin drive?', a: 'I-35 from OKC to Austin is approximately 400 miles, 5.5 hours. Highway is straightforward (no mountain passes). Most families also fly: 1.5-hour direct flights on American and Southwest, round-trip $150-$280.' },
    ],
    published: true,
  },
  {
    slug: 'missouri',
    name: 'Missouri',
    abbr: 'MO',
    primaryAirport: 'STL/MCI',
    flightTimeToAustinHours: 2.0,
    drivingDistanceToAustinMiles: 880,
    publicCollegeInState: 'University of Missouri',
    inStateTuitionPublicUSD: 12_600,
    costOfLivingNote: 'St. Louis and Kansas City cost of living runs about 25-30% below Austin (housing is the largest differential). Missouri state income tax tops at 4.95% (recently reduced); Texas has zero. The tax move is meaningful for high earners ($8,000-$20,000/year savings on six-figure incomes).',
    notableFamiliesContext: 'Missouri families consider UT for CS, McCombs, and the Austin economic context. Both St. Louis and Kansas City have strong tech and finance employment, but the Austin opportunity ecosystem (Apple, Google, Meta, plus startups) is larger. Mizzou is a respected flagship but lacks the depth UT has in business and computer science.',
    residencyMoveNote: 'Missouri residency is straightforward to exit. Standard documentary set establishes Texas residency in 12 months. Missouri-to-Texas tax move saves $8,000-$20,000/year for upper-middle and high-earner households. The 9-hour drive from St. Louis to Austin makes occasional travel back to Missouri manageable.',
    faq: [
      { q: 'Is UT better than Mizzou?', a: 'For McCombs Business, UT outranks the Trulaske College of Business by a wide margin. UT CS and Cockrell Engineering similarly outrank Mizzou comparable programs. For Journalism, Mizzou is one of the top programs in the country (the J-School is a particular distinction). For most other majors, UT is the academically stronger choice.' },
      { q: 'Is Missouri cheap enough that the move does not make sense?', a: 'Missouri in-state at $12,600 is about $900/year more expensive than UT in-state at $11,688. The Texas residency pathway saves about $99,660 in tuition over 3 years vs UT non-resident. The state tax move ($8,000-$20,000/year for high earners) is the additional ongoing benefit. For most families, the move pencils.' },
      { q: 'How does Missouri-to-Texas tax compare?', a: 'Missouri top rate is 4.95%; Texas zero. For a $300K AGI household, savings is approximately $14,800/year. Lower-income households see smaller absolute savings but larger as a percentage of income.' },
      { q: 'How is the STL-to-Austin flight?', a: '2 hours direct on Southwest, American. Round-trip fares $180-$350. Manageable for weekend trips back to Missouri.' },
    ],
    published: true,
  },
  {
    slug: 'connecticut',
    name: 'Connecticut',
    abbr: 'CT',
    primaryAirport: 'BDL/JFK',
    flightTimeToAustinHours: 3.75,
    drivingDistanceToAustinMiles: 1900,
    publicCollegeInState: 'University of Connecticut',
    inStateTuitionPublicUSD: 18_300,
    costOfLivingNote: 'Fairfield County (Greenwich, Westport, New Canaan) is among the most expensive US areas; Hartford and New Haven are more moderate but still above national average. Connecticut state income tax tops at 6.99%; Texas zero. For Connecticut families relocating to Austin, the combined Connecticut income tax and property tax escape can save $30,000-$80,000/year for upper-income households.',
    notableFamiliesContext: 'Connecticut families typically consider UT for CS, McCombs, and the Austin tech-and-finance context. Many Connecticut families work in NYC and would have the option of NYU or Columbia at private rates; UT offers a strong public option with the residency pathway. The Connecticut-to-Austin move is favored by tech-industry families looking to escape the Northeast tax burden while keeping a strong-flagship education for their student.',
    residencyMoveNote: 'Connecticut residency is straightforward to exit but the Connecticut Department of Revenue Services is among the more aggressive in pursuing former-resident audits, particularly for high earners. The move should be clean: sell or fully rent out the Connecticut property, cancel Connecticut voter registration, surrender Connecticut driver\'s license, file part-year Connecticut tax return for the transition year. Most Connecticut families work with CPAs experienced in Connecticut-to-Texas moves.',
    faq: [
      { q: 'Is UConn comparable to UT for in-state Connecticut students?', a: 'UConn in-state at $18,300 is about $6,600/year more expensive than UT in-state at $11,688. UT generally outranks UConn academically in business and computer science. UConn is strong in pharmacy, education, and engineering. For students admitted to McCombs or UT CS, the academic upgrade plus the cost savings makes UT the clear choice (assuming the residency pathway is feasible).' },
      { q: 'How does Connecticut-to-Texas state tax compare?', a: 'Connecticut top rate is 6.99%; Texas zero. For a $500K AGI household, savings is approximately $35,000/year. For a $1M+ household, savings can exceed $70,000/year. This is the second-largest motivator (after tuition) for many Connecticut-to-Austin moves.' },
      { q: 'Is Connecticut\'s exit audit a real concern?', a: 'Yes. Connecticut DRS has been aggressive about pursuing former-resident high earners who claim to have moved. The move must be clean: no Connecticut driver\'s license, no Connecticut voter registration, no Connecticut-resident tax return going forward. Document the move thoroughly with moving company records, lease termination, utility shutoffs, and the new Texas documentary set.' },
      { q: 'How is the BDL-to-Austin flight?', a: '3.75 hours direct on Southwest, American, JetBlue. Round-trip fares $250-$500. Also flyable from JFK or LaGuardia with similar timing.' },
    ],
    published: true,
  },
  {
    slug: 'louisiana',
    name: 'Louisiana',
    abbr: 'LA',
    primaryAirport: 'MSY',
    flightTimeToAustinHours: 1.25,
    drivingDistanceToAustinMiles: 510,
    publicCollegeInState: 'Louisiana State University',
    inStateTuitionPublicUSD: 12_200,
    costOfLivingNote: 'New Orleans and Baton Rouge cost of living is generally lower than Austin (housing runs 20-30% cheaper). Louisiana state income tax tops at 4.25%; Texas zero. The Louisiana-to-Texas move saves modest state tax ($5,000-$15,000/year for high earners) plus property tax differences vary by parish.',
    notableFamiliesContext: 'Louisiana families consider UT for CS, McCombs, Cockrell Engineering, and the Austin/Texas economic context. The 510-mile drive (8 hours) from New Orleans to Austin makes weekend visits practical. Many Louisiana families also have Texas business ties (oil and gas, Gulf Coast logistics) making the Texas move feel natural.',
    residencyMoveNote: 'Louisiana residency is straightforward to exit. Standard documentary set establishes Texas residency in 12 months. Louisiana-to-Texas move is geographically and culturally easy (both states share Gulf Coast culture and economic ties). The tax move is meaningful but smaller than from California or New York.',
    faq: [
      { q: 'Why move from Louisiana to Texas when LSU is comparable?', a: 'LSU in-state at $12,200 is about $500/year more expensive than UT in-state at $11,688. UT generally outranks LSU academically in business (McCombs vs LSU Ourso) and computer science. LSU is strong in geosciences (oil and gas), agriculture, and athletic tradition. For students admitted to McCombs, CS, or Cockrell, UT is the academic upgrade plus the Texas tax move is the household financial benefit.' },
      { q: 'How does Louisiana-to-Texas tax compare?', a: 'Louisiana top rate is 4.25%; Texas zero. For a $200K AGI household, savings is approximately $6,500/year. For a $500K household, savings is approximately $18,000/year. Plus Texas property tax can be higher than Louisiana property tax depending on parish vs Texas county; net the comparison.' },
      { q: 'How is the New Orleans-to-Austin flight?', a: '1.25 hours direct on Southwest, American, United. Round-trip fares $150-$300. Easy weekend visits. Drive option: 8 hours via I-10.' },
      { q: 'What about Louisiana-Texas Gulf Coast business ties?', a: 'Many Louisiana families with Gulf Coast business ties (oil and gas, logistics, petrochemicals) find the move to Texas seamless. Texas\'s energy industry concentration in Houston and the Permian basin parallels Louisiana\'s, making it a natural professional transition. For families in this business sector, the move is often already in progress through job-related relocation.' },
    ],
    published: true,
  },
  {
    slug: 'south-carolina',
    name: 'South Carolina',
    abbr: 'SC',
    primaryAirport: 'CHS/CLT',
    flightTimeToAustinHours: 2.5,
    drivingDistanceToAustinMiles: 1100,
    publicCollegeInState: 'University of South Carolina',
    inStateTuitionPublicUSD: 12_700,
    costOfLivingNote: 'Charleston housing has risen significantly in the past decade but remains below Austin in most submarkets. Greenville and Columbia are materially cheaper. South Carolina state income tax tops at 6.4% (transitioning to 6.2%); Texas zero. The tax move saves $5,000-$20,000/year for higher-income households.',
    notableFamiliesContext: 'South Carolina families consider UT for CS, McCombs, Cockrell Engineering, and the broader Texas opportunity ecosystem. Charleston\'s growing tech and finance presence parallels Austin\'s but at smaller scale. Many South Carolina families have business or military ties to Texas already.',
    residencyMoveNote: 'South Carolina residency is straightforward to exit. Standard documentary set establishes Texas residency in 12 months. The tax savings from exiting South Carolina\'s income tax ($5,000-$20,000/year) plus the tuition pathway ($99,660 over 3 years) typically pencils well for families with $200K+ AGI.',
    faq: [
      { q: 'Is UT or USC (University of South Carolina) better?', a: 'For most academic comparisons, UT outranks USC South Carolina. McCombs Business significantly outranks the Darla Moore School of Business (though Darla Moore is well-regarded for International Business). UT CS and Cockrell outrank USC SC equivalents. For students admitted to McCombs, UT CS, or Cockrell, UT is the academically stronger choice.' },
      { q: 'How does South Carolina-to-Texas state tax compare?', a: 'South Carolina top rate is 6.4%; Texas zero. For a $300K AGI household, savings is approximately $19,000/year.' },
      { q: 'How is the Charleston-to-Austin flight?', a: '2.5 hours direct on American (limited) or one-stop via CLT (Charlotte). Round-trip fares $250-$500. CLT-to-Austin direct is common.' },
      { q: 'Can my Charleston family bring our business?', a: 'Many service businesses, consulting practices, and remote-work-friendly professional firms transition smoothly to Texas. Texas\'s lack of state income tax and pro-business regulatory environment makes the move particularly favorable for higher-income service professionals.' },
    ],
    published: true,
  },
  {
    slug: 'alabama',
    name: 'Alabama',
    abbr: 'AL',
    primaryAirport: 'BHM/HSV',
    flightTimeToAustinHours: 2.0,
    drivingDistanceToAustinMiles: 800,
    publicCollegeInState: 'University of Alabama',
    inStateTuitionPublicUSD: 11_900,
    costOfLivingNote: 'Birmingham, Huntsville, and Tuscaloosa have lower cost of living than Austin in nearly every category. Alabama state income tax tops at 5%; Texas zero. The tax move saves modest amounts for most households.',
    notableFamiliesContext: 'Alabama families consider UT for CS, McCombs, and the Austin economic context. Huntsville\'s growing aerospace and defense industry connects to Texas\'s broader aerospace sector. University of Alabama in-state is competitive on cost but UT generally outranks Alabama academically in business and computer science.',
    residencyMoveNote: 'Alabama residency is straightforward to exit. Standard documentary set establishes Texas residency in 12 months. Alabama-to-Texas tax move saves $3,000-$15,000/year for higher-income households.',
    faq: [
      { q: 'Is UT better than Alabama?', a: 'For most academic comparisons, UT outranks Alabama. McCombs Business significantly outranks Culverhouse College of Business. UT CS and Cockrell Engineering outrank Alabama equivalents. Alabama has strong programs in Communications (especially journalism) and athletics tradition (Crimson Tide football).' },
      { q: 'Is Alabama cheaper than UT for in-state students?', a: 'Yes, marginally. Alabama in-state at $11,900 is about $200/year more expensive than UT in-state at $11,688. The two are essentially the same cost for residents.' },
      { q: 'How does Alabama-to-Texas tax compare?', a: 'Alabama top rate is 5%; Texas zero. For a $200K AGI household, savings is approximately $7,000/year. Higher-income households see proportionally larger savings.' },
      { q: 'How is the BHM-to-Austin flight?', a: '2 hours direct on Southwest, American. Round-trip fares $200-$400. Manageable for weekend visits.' },
    ],
    published: true,
  },
  {
    slug: 'kentucky',
    name: 'Kentucky',
    abbr: 'KY',
    primaryAirport: 'SDF/LEX',
    flightTimeToAustinHours: 2.25,
    drivingDistanceToAustinMiles: 1000,
    publicCollegeInState: 'University of Kentucky',
    inStateTuitionPublicUSD: 13_400,
    costOfLivingNote: 'Louisville and Lexington cost of living runs about 25-35% below Austin (housing is the largest differential). Kentucky state income tax is a flat 4%; Texas zero. The tax move saves $5,000-$15,000/year for higher-income households.',
    notableFamiliesContext: 'Kentucky families consider UT for CS, McCombs, Cockrell, and the Austin opportunity ecosystem. Louisville\'s healthcare and logistics economy and Lexington\'s growing tech base are smaller than Austin\'s tech scene. UK in-state is more expensive than UT in-state, making the Texas pathway favorable.',
    residencyMoveNote: 'Kentucky residency is straightforward to exit. Standard documentary set establishes Texas residency in 12 months. The Kentucky-to-Texas move saves $5,000-$15,000/year in state tax plus the substantial UT tuition pathway savings.',
    faq: [
      { q: 'Is UT cheaper than Kentucky for in-state students?', a: 'Yes. Kentucky in-state at $13,400 is about $1,700/year more expensive than UT in-state at $11,688. The Texas residency pathway is favorable on tuition alone.' },
      { q: 'Is UT better than Kentucky?', a: 'For most academic comparisons, yes. McCombs Business significantly outranks Gatton College of Business. UT CS and Cockrell outrank Kentucky equivalents. Kentucky has strong programs in equine industry studies (Lexington horse industry) and a strong basketball tradition.' },
      { q: 'How does Kentucky-to-Texas tax compare?', a: 'Kentucky flat 4%; Texas zero. For a $250K AGI household, savings is approximately $10,000/year.' },
      { q: 'How is the Louisville-to-Austin flight?', a: '2.25 hours direct on Southwest, American. Round-trip fares $200-$400. Manageable for weekend visits. Drive option: 12 hours via I-65 and I-40.' },
    ],
    published: true,
  },
  {
    slug: 'oregon',
    name: 'Oregon',
    abbr: 'OR',
    primaryAirport: 'PDX',
    flightTimeToAustinHours: 4.0,
    drivingDistanceToAustinMiles: 2050,
    publicCollegeInState: 'University of Oregon',
    inStateTuitionPublicUSD: 14_700,
    costOfLivingNote: 'Portland and Eugene cost of living is comparable to or slightly above Austin in most submarkets. Bend has risen significantly. Oregon state income tax tops at 9.9% (one of the highest in the country); Texas zero. The tax move alone saves $15,000-$60,000/year for high earners.',
    notableFamiliesContext: 'Oregon families consider UT for CS, McCombs, and the lower cost basis of Texas. Portland\'s tech industry is strong (Nike HQ, Intel campus, growing startup base) but the Oregon tax burden plus the UT-vs-Oregon ranking gap makes the move favorable for many families. Many Oregon-to-Austin families are tech-industry professionals taking advantage of remote work.',
    residencyMoveNote: 'Oregon residency exit is straightforward but Oregon Department of Revenue tracks former residents on high incomes. Document the move cleanly: sell or fully rent out Oregon property, cancel Oregon voter registration, surrender Oregon driver\'s license, file part-year Oregon tax return for the transition year. The 9.9% income tax exit is a major driver for Oregon families.',
    faq: [
      { q: 'Is UT better than Oregon?', a: 'For most academic comparisons, yes. McCombs Business significantly outranks Lundquist College of Business. UT CS outranks Oregon CS. Oregon has strong programs in journalism, music, and the natural sciences. For most majors, UT is the academically stronger choice.' },
      { q: 'Is Oregon cheaper than UT for in-state students?', a: 'No. Oregon in-state at $14,700 is about $3,000/year more expensive than UT in-state at $11,688. UT is the cheaper option for Oregon residents who establish Texas residency.' },
      { q: 'How does Oregon-to-Texas state tax compare?', a: 'Oregon top rate is 9.9%; Texas zero. For a $500K AGI household, savings is approximately $48,000/year. Oregon\'s tax burden is one of the highest in the country, making the Texas move particularly favorable for high earners.' },
      { q: 'How is the PDX-to-Austin flight?', a: '4 hours direct on Alaska, Southwest, American. Round-trip fares $250-$500. Long but manageable for occasional trips.' },
      { q: 'Can my Portland tech professional family work remotely from Austin?', a: 'Yes. Many Portland-to-Austin moves are tech professionals who maintain employment with Pacific Northwest or Bay Area companies while living in Texas. The tech industry is fully accommodating of remote work, and the Texas tax advantages plus lower cost of living make the move financially favorable for high-earning tech workers.' },
    ],
    published: true,
  },
  {
    slug: 'iowa',
    name: 'Iowa',
    abbr: 'IA',
    primaryAirport: 'DSM/CID',
    flightTimeToAustinHours: 2.0,
    drivingDistanceToAustinMiles: 950,
    publicCollegeInState: 'University of Iowa',
    inStateTuitionPublicUSD: 10_500,
    costOfLivingNote: 'Des Moines, Cedar Rapids, and Iowa City have cost of living about 25-30% below Austin (housing primarily). Iowa state income tax tops at 5.7% (recently reduced from 8.53%); Texas zero.',
    notableFamiliesContext: 'Iowa families consider UT for CS, McCombs, Cockrell, and the Austin opportunity ecosystem. Iowa is a strong public flagship but UT offers materially stronger business and CS programs. Many Iowa families have agricultural or insurance industry ties that may or may not translate to Texas.',
    residencyMoveNote: 'Iowa residency is straightforward to exit. Standard documentary set establishes Texas residency in 12 months. The tax move ($5,000-$20,000/year savings for higher earners) plus the tuition pathway makes UT favorable for high-academic Iowa students.',
    faq: [
      { q: 'Is UT cheaper than Iowa for in-state students?', a: 'No. Iowa in-state at $10,500 is about $1,200/year cheaper than UT in-state at $11,688. For Iowa-resident families, the in-state comparison favors Iowa.' },
      { q: 'Is UT better than Iowa?', a: 'For most academic comparisons, yes. McCombs significantly outranks Tippie College of Business. UT CS and Cockrell outrank Iowa equivalents. Iowa has strong programs in Creative Writing (Iowa Writers\' Workshop is world-famous), nursing, and journalism.' },
      { q: 'How does Iowa-to-Texas state tax compare?', a: 'Iowa flat 5.7% (top rate); Texas zero. For a $200K AGI household, savings is approximately $8,000/year.' },
      { q: 'How is the DSM-to-Austin flight?', a: '2 hours direct on Southwest, American. Round-trip fares $200-$400.' },
    ],
    published: true,
  },
  {
    slug: 'kansas',
    name: 'Kansas',
    abbr: 'KS',
    primaryAirport: 'MCI/ICT',
    flightTimeToAustinHours: 1.75,
    drivingDistanceToAustinMiles: 750,
    publicCollegeInState: 'University of Kansas',
    inStateTuitionPublicUSD: 11_800,
    costOfLivingNote: 'Kansas City and Wichita cost of living runs about 20-25% below Austin. Kansas state income tax tops at 5.7%; Texas zero. The tax move saves moderate amounts.',
    notableFamiliesContext: 'Kansas families consider UT for CS, McCombs, and the Austin opportunity ecosystem. KU is competitive but UT generally outranks. Geographic adjacency makes Texas an accessible move.',
    residencyMoveNote: 'Kansas residency is straightforward to exit. Standard documentary set establishes Texas residency in 12 months. The 750-mile drive from Kansas City to Austin makes maintenance manageable.',
    faq: [
      { q: 'Is UT or KU cheaper for in-state students?', a: 'Comparable. KU in-state at $11,800 is roughly the same as UT in-state at $11,688. The two are essentially equivalent on tuition cost for residents.' },
      { q: 'Is UT better than KU?', a: 'For most academic comparisons, yes. McCombs significantly outranks KU School of Business. UT CS and Cockrell outrank KU equivalents. KU has strong programs in journalism, pharmacy, and basketball tradition.' },
      { q: 'How does Kansas-to-Texas state tax compare?', a: 'Kansas top rate 5.7%; Texas zero. For a $250K AGI household, savings is approximately $10,000/year.' },
      { q: 'How is the Kansas City-to-Austin flight?', a: '1.75 hours direct on Southwest, American. Round-trip fares $180-$350.' },
    ],
    published: true,
  },
  {
    slug: 'utah',
    name: 'Utah',
    abbr: 'UT',
    primaryAirport: 'SLC',
    flightTimeToAustinHours: 2.75,
    drivingDistanceToAustinMiles: 1300,
    publicCollegeInState: 'University of Utah',
    inStateTuitionPublicUSD: 10_400,
    costOfLivingNote: 'Salt Lake City and Provo housing has risen significantly but remains below Austin. Utah state income tax is a flat 4.65%; Texas zero. The tax move saves $5,000-$25,000/year for higher earners.',
    notableFamiliesContext: 'Utah families consider UT for CS, McCombs, and the Austin opportunity ecosystem. Utah is strong in CS and engineering; UT generally competitive. The Mormon/LDS community is a meaningful cultural factor in Utah; Austin is more secular.',
    residencyMoveNote: 'Utah residency is straightforward to exit. Standard documentary set establishes Texas residency in 12 months. The 1,300-mile distance from Salt Lake to Austin makes the move more substantial than from neighboring states.',
    faq: [
      { q: 'Is UT cheaper than Utah for in-state students?', a: 'No. Utah in-state at $10,400 is about $1,300/year cheaper than UT in-state at $11,688. For Utah-resident families, the in-state comparison favors Utah.' },
      { q: 'Is UT better than Utah?', a: 'For most academic comparisons, yes. McCombs significantly outranks Eccles School of Business. UT CS and Cockrell are competitive with Utah equivalents. Utah is strong in CS and engineering, particularly in graphics and entertainment software.' },
      { q: 'How does Utah-to-Texas state tax compare?', a: 'Utah flat 4.65%; Texas zero. For a $300K AGI household, savings is approximately $14,000/year.' },
      { q: 'How is the SLC-to-Austin flight?', a: '2.75 hours direct on Southwest, Delta, American. Round-trip fares $250-$500.' },
    ],
    published: true,
  },
  {
    slug: 'nevada',
    name: 'Nevada',
    abbr: 'NV',
    primaryAirport: 'LAS/RNO',
    flightTimeToAustinHours: 2.5,
    drivingDistanceToAustinMiles: 1350,
    publicCollegeInState: 'University of Nevada, Reno',
    inStateTuitionPublicUSD: 9_400,
    costOfLivingNote: 'Las Vegas housing has risen significantly; Reno is more moderate. Nevada has no state income tax; Texas zero. The tax move is not a driver (both states zero).',
    notableFamiliesContext: 'Nevada families consider UT for CS, McCombs, and the Austin opportunity ecosystem. UNR and UNLV are accessible but UT outranks academically. The Nevada-to-Texas move is primarily about UT\'s academic offerings rather than tax considerations.',
    residencyMoveNote: 'Nevada residency is straightforward to exit. Standard documentary set establishes Texas residency in 12 months. The tax-burden picture is similar between the two states (both no income tax); the move is about UT specifically rather than household tax optimization.',
    faq: [
      { q: 'Is UT cheaper than UNR/UNLV for in-state students?', a: 'No. UNR/UNLV in-state at $9,400 is about $2,300/year cheaper than UT in-state at $11,688. For Nevada-resident families, the in-state comparison favors Nevada.' },
      { q: 'Is UT better than Nevada?', a: 'For most academic comparisons, yes. McCombs significantly outranks UNR/UNLV business. UT CS and Cockrell outrank Nevada equivalents. Nevada has unique programs in hospitality (UNLV Harrah College of Hospitality) that UT does not match.' },
      { q: 'How does Nevada-to-Texas state tax compare?', a: 'Both states have zero income tax; no tax move advantage from this comparison.' },
      { q: 'How is the LAS-to-Austin flight?', a: '2.5 hours direct on Southwest, American. Round-trip fares $200-$400.' },
    ],
    published: true,
  },
];

export const getState = (slug: string) => STATES.find(s => s.slug === slug && s.published);
export const publishedStates = () => STATES.filter(s => s.published);
